---
title: "Course project 1"
author: "pmakai"
date: "1 januari 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path = "figure/")
(echo = TRUE)
```

Reading in the data

```{r}
echo=TRUE
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip",temp)
d <- read.csv(unz(temp, "activity.csv"), sep=",", header=TRUE)
d$date<-as.Date(d$date)
unlink(temp)
```

#Mean steps per day

##Histogram
```{r}
echo=TRUE
d1<-aggregate(steps~date,data=d,sum)
hist(d1$steps, main="Mean number of steps", xlab="Steps")
```

##Mean

```{r}
echo=TRUE
mean(d1$steps)
```

##Median

```{r}
echo=TRUE
median(d1$steps)
```

#Average daily activity pattern

```{r}
d2<-aggregate(steps~interval, d, mean)
plot(d2$interval, d2$steps, type='l', col=1, main="Average number of steps by Interval", xlab="Time Intervals", ylab="Average number of steps")
```

##Maximum

```{r}
int <- which.max(d2$steps)
d2[int,]
```

#Missing data
##Number of missing values
```{r}
mis <- length(which(is.na(d$steps)))
```

##Imputing means

```{r}
#obtain mean, merge back to file and replace missing values
a<-aggregate(steps~interval,data=d,mean)
a$mean<-a$steps
a$steps<-NULL
i<-merge(d,a, by="interval",all=TRUE)
i$steps[is.na(i$steps)]<-i$mean[is.na(i$steps)]
```

##Historam with imputed values

```{r}
i1<-aggregate(steps~date,data=i,sum)
hist(i1$steps, main="Mean number of steps", xlab="Steps")
```

```{r}
mean(i1$steps)
median(i1$steps)
```

##Creating a weekday weekend variable

```{r}
i$weekday <-  ifelse(as.POSIXlt(i$date)$wday %in% c(0,6), 'weekend', 'weekday')
```

##Time series plot

```{r}

require(ggplot2)
i2 <- aggregate(steps ~ interval + weekday, data=i, mean)
ggplot(i2, aes(interval, steps)) + 
    geom_line() + 
    facet_grid(weekday ~ .) +
    xlab("5-minute interval") + 
    ylab("avarage number of steps")
```